<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "Aldon WIKI",
    "slogan": "",
    "description": "",
    "footer": "",
    "itemsPerPage": 6,
    "language": "nl_NL",
    "locale": "nl_NL",
    "timezone": "Europe\/Amsterdam",
    "theme": "typerite",
    "adminTheme": "booty",
    "homepage": "create-your-own-content",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "\/blog\/",
    "url": "http:\/\/localhost\/aldonwiki\/",
    "emailFrom": "no-reply@localhost",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "",
    "facebook": "",
    "codepen": "",
    "github": "",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "thumbnailWidth": 400,
    "thumbnailHeight": 400,
    "thumbnailQuality": 100,
    "markdownParser": true,
    "customFields": "[]"
}